--Mysql
SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
            GENDER ='W'
        AND
        MONTH(DATE_OF_BIRTH) = 3
  AND
    TLNO IS NOT NULL
ORDER BY
    MEMBER_ID;



--Oracle

SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
        GENDER ='W'
  AND
        TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
  AND
    TLNO IS NOT NULL
ORDER BY
    MEMBER_ID;