SELECT 
    COUNT(F1.ID) AS FISH_COUNT,
    F2.FISH_NAME
FROM 
    FISH_INFO AS F1
    JOIN
        FISH_NAME_INFO AS F2
    ON 
        F1.FISH_TYPE = F2.FISH_TYPE
GROUP BY
    FISH_NAME
ORDER BY
    FISH_COUNT DESC;