SELECT
    ED.ID,
    ED.GENOTYPE,
    ED2.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA ED
        JOIN
    ECOLI_DATA ED2 ON ED.PARENT_ID = ED2.ID
WHERE
    (ED.GENOTYPE | ED2.GENOTYPE) = ED.GENOTYPE
ORDER BY
    ED.ID;
