SELECT
    HD.DEPT_ID,
    HD.DEPT_NAME_EN,
    --AVG(ROUND(HE.SAL, 0)) AS AVG_SAL -- 평균 구한 뒤에 반올림 하는 것이 맞는 계산
    ROUND(AVG(HE.SAL), 0) AS AVG_SAL
FROM
    HR_DEPARTMENT HD
    JOIN
        HR_EMPLOYEES HE
    ON
        HD.DEPT_ID = HE.DEPT_ID
GROUP BY
    HD.DEPT_ID,
    HD.DEPT_NAME_EN
ORDER BY
    AVG_SAL DESC;

