--Mysql
SELECT
    YEAR,
    MONTH,
    COUNT(*) AS PUCHASED_USERS,
    ROUND((COUNT(*) / (
    SELECT
    COUNT(*)
    FROM
    USER_INFO
    WHERE
    YEAR(JOINED) = 2021)), 1
    ) AS PUCHASED_RATIO
FROM (
    SELECT
    DISTINCT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    U.USER_ID
    FROM
    ONLINE_SALE S
    JOIN
    USER_INFO U
    ON
    S.USER_ID = U.USER_ID
    AND
    YEAR(JOINED) = 2021
    ) O
GROUP BY
    YEAR,
    MONTH
ORDER BY
    YEAR,
    MONTH


--Oracle
SELECT
    DISTINCT
    YEAR,
    MONTH,
    PUCHASED_USERS,
    ROUND(PUCHASED_USERS / (
    SELECT
    COUNT(*)
    FROM
    USER_INFO
    WHERE
    TO_CHAR(JOINED, 'YYYY')='2021'), 1
    ) PUCHASED_RATIO
FROM (
    SELECT
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')) YEAR,
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')) MONTH,
    COUNT(DISTINCT U.USER_ID) OVER (
    PARTITION BY
    TO_CHAR(S.SALES_DATE, 'YYYY'),
    TO_CHAR(S.SALES_DATE, 'FMMM')) PUCHASED_USERS
    FROM
    ONLINE_SALE S
    JOIN
    USER_INFO U
    ON
    S.USER_ID = U.USER_ID
    WHERE
    TO_CHAR(U.JOINED, 'YYYY') = '2021')
ORDER BY
    YEAR,
    MONTH
