WITH WITHYEAR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
    )


SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (WY.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM
    ECOLI_DATA ED
    JOIN
        WITHYEAR WY
    ON
        YEAR(ED.DIFFERENTIATION_DATE) = WY.YEAR
ORDER BY
    YEAR,
    YEAR_DEV,
    ID;
