-- Oracle
SELECT
    B.TITLE AS TITLE,
    B.BOARD_ID AS BOARD_ID,
    R.REPLY_ID AS REPLY_ID,
    R.WRITER_ID AS WRITER_ID,
    R.CONTENTS AS CONTENTS,
    TO_CHAR(R.CREATED_DATE, 'yyyy-mm-dd') AS CREATED_DATE
FROM
    USED_GOODS_BOARD B,
    USED_GOODS_REPLY R
WHERE
        B.BOARD_ID = R.BOARD_ID
  AND
    B.CREATED_DATE
        BETWEEN
        TO_DATE('2022-10-01', 'yyyy-mm-dd')
        AND TO_DATE('2022-10-31','yyyy-mm-dd')
ORDER BY
    R.CREATED_DATE ASC,
    B.TITLE ASC;

--Mysql
SELECT
    B.TITLE AS TITLE,
    B.BOARD_ID AS BOARD_ID,
    R.REPLY_ID AS REPLY_ID,
    R.WRITER_ID AS WRITER_ID,
    R.CONTENTS AS CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM
    USED_GOODS_BOARD B
        JOIN USED_GOODS_REPLY R
             ON B.BOARD_ID = R.BOARD_ID
WHERE
        B.CREATED_DATE LIKE '2022-10%'
ORDER BY
    R.CREATED_DATE ASC,
    B.TITLE ASC;