--Mysql
SELECT
    USER_ID,
    NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS B
        JOIN
    USED_GOODS_USER AS U
    ON
            B.WRITER_ID = U.USER_ID
WHERE
        STATUS = 'DONE' #완료된 중고 거래
GROUP BY
    USER_ID
HAVING
    TOTAL_SALES >= 700000 #총금액 70만원 이상
ORDER BY
    TOTAL_SALES ASC;


--Oracle
SELECT
    U.USER_ID AS USER_ID,
    U.NICKNAME AS NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD B
        JOIN
    USED_GOODS_USER U
    ON
            B.WRITER_ID = U.USER_ID
WHERE
        STATUS = 'DONE'
GROUP BY
    USER_ID,
    NICKNAME
HAVING
        SUM(PRICE) >= 700000
ORDER BY
    TOTAL_SALES
